version: '3.8'

services:
  app:
    build: .
    container_name: golang_server
    depends_on:
      - db
    environment:
      HTTP_PORT: 8080
      POSTGRES_DB: example
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: example
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5432
      POSTGRES_SSLMODE: disable
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
